steps:
- name: 'ubuntu'
  args: ['bash', './myscript.bash']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/alejandro-riquelme/ubuntu', '.']
images: ['gcr.io/alejandro-riquelme/ubuntu']
